version: '3.3'
services:
    rnd10bis-api:
        container_name: 'rnd10bis-api'
        build: './Server'
        ports:
            - '9000:9000'
        networks:
            - routertest
    rnd10bis-client:
        container_name: 'rnd10bis-client'
        build: './Client'
        ports:
            - 80:80
        depends_on:
            - 'rnd10bis-api'
        networks:
            - routertest
networks:
    routertest:
        driver: bridge
